# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Загловок'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='Статья',
        ),
    ]
