# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20170829_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_create'], 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='datetime',
        ),
        migrations.AddField(
            model_name='article',
            name='date_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
